# Generated by cucumber-sinatra. (2010-09-28 23:56:49 +0100)

require File.join(File.dirname(__FILE__), '..', '..', 'lib/ykk_tour.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

YkkTour.set(:environment, :test)

Capybara.app = YkkTour

class YkkTourWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  YkkTourWorld.new
end
