# Generated by cucumber-sinatra. (2010-10-03 22:39:34 +0100)

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

YkkTour.set(:environment, :test)

Capybara.app = YkkTour

class YkkTourWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  YkkTourWorld.new
end
